### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by JonCrawford** [fcoury/atom-rspec#65]
[Enter steps to reproduce below:]

1. Get a test to fail.
2. Click on the link to open the failing test's spec file.
3. Error!

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [rspec](https://github.com/fcoury/atom-rspec) package, v0.3.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jon/.dotfiles/atom.symlink/packages/rspec/lib/rspec-view.coffee:61

TypeError: undefined is not a function
  at RSpecView.module.exports.RSpecView.terminalClicked (/Users/jon/.dotfiles/atom.symlink/packages/rspec/lib/rspec-view.coffee:61:30)
  at HTMLPreElement.<anonymous> (/Users/jon/.dotfiles/atom.symlink/packages/rspec/lib/rspec-view.coffee:1:1)
  at HTMLPreElement.jQuery.event.dispatch (/Users/jon/.apps/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLPreElement.elemData.handle (/Users/jon/.apps/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".bundle",
      ".git",
      "log",
      "repositories",
      "tmp",
      "vendor"
    ],
    "disabledPackages": [
      "exception-reporting",
      "metrics",
      "autocomplete",
      "linter-scss-lint",
      "atom-lint",
      "linter"
    ],
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/Users/jon/Sites/"
  },
  "rspec": {
    "command": "spring rspec",
    "save_before_run": true,
    "force_colored_results": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.9
autocomplete-ruby, v0.1.0
circle-ci, v0.10.0
color-picker, v2.0.4
coverage, v0.6.1
emmet, v2.3.10
file-icons, v1.5.7
jshint, v1.3.7
language-rspec, v0.3.0
linter-csslint, v0.0.13
linter-erb, v0.1.1
pretty-json, v0.3.3
project-manager, v1.15.10
react, v0.12.0
remote-atom, v1.2.6
rspec, v0.3.1
ruby-slim, v0.2.0
slack-chat, v1.0.1
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by matugm** [comment]
Thanks for your report. I think this is related to https://github.com/fcoury/atom-rspec/pull/63 so it should be fixed in the next version.

**Comment by JonCrawford** [comment]
:+1: Thanks for being awesome!
