### ISSUE TITLE
Failed to activate the rspec package

### ISSUE THREAD

**Issue by Focinfi** [fcoury/atom-rspec#71]
**I cloned this repository directly in .atom/packages**

1. Move the cursor to it "...."
2. Alt+Ctrl+T

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10
**Thrown From**: [rspec](https://github.com/fcoury/atom-rspec) package, v0.3.3

### Stack Trace

Failed to activate the rspec package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/mac/.atom/packages/atom-rspec/lib/rspec-view.coffee:1:36)
  at Object.<anonymous> (/Users/mac/.atom/packages/atom-rspec/lib/rspec-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/mac/.atom/packages/atom-rspec/lib/rspec.coffee:1:13)
  at Object.<anonymous> (/Users/mac/.atom/packages/atom-rspec/lib/rspec.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:239:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:792:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:25.4.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:24.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:22.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:06.1.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 rspec:run (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by Focinfi** [comment]
Hum, I think I didn't install in a right way.

`apm install rspec` is fine.
